### ISSUE TITLE
name 'num_lines' is not defined in tf2_hisan.py 

### ISSUE THREAD

**Issue by tinaty** [iamshang1/Projects#1]
Hi Shang,
Thank you for creating tf2 version of HiSAN. When I tried to run the codes, it showed an error in line 94 _line_embeds = tf.reshape(word_targ_out,(num_lines,1,self.attention_size))_ that NameError: name 'num_lines' is not defined.  Could you please advise if/how this issue can be fixed?
Thank you in advance.
Regards,
Tina

**Comment by iamshang1** [comment]
Looks like a few extra lines got through in there by accident. Let me know if the issue persists.

**Comment by iamshang1** [comment]
Looks like it was a bad merge, and some duplicate lines got added to the code. I think I've removed them all, let me know if there are any issues still.

**Comment by tinaty** [comment]
Now it works very well, thanks so much for fixing it.
